# 1. Используем явную версию
FROM jupyterhub/jupyterhub:3.1.1

# 2. Оптимизируем слои. Часто меняющиеся библиотеки питона выделены в отдельный слой.
#     В идеале, конечно, использовать requirements.txt для библиотек питона.
# 3. Очищаем кэш менеджеров пакетов. 
RUN apt update \
    && apt -y install python3-dev git \
    && apt clean
RUN pip install --no-cache-dir \
    numpy==1.24.3 \
    pandas==2.1.4 \
    matplotlib==3.8.2 

WORKDIR /jupyter

# 4. Копируем только нужные файлы
COPY my_file.txt .

VOLUME /volume

# Изменили ENTRYPOINT на JSON формат.
ENTRYPOINT ["jupyterhub", "--log-level=DEBUG"]
